Diagnostics:
  UnusedIncludes: Strict
  ClangTidy:
    Add: [
      google-*,
      misc-*,
      bugprone-*,
      boost-*,
      clang-analyzer-*,
      concurrency-*,
      modernize-*,
      performance-*,
      portability-*,
      readability-*",
      cppcoreguidelines-no-malloc,
      cppcoreguidelines-pro-bounds-constant-array-index,
      cppcoreguidelines-pro-type-static-cast-downcast,
      cppcoreguidelines-pro-type-const-cast,
      cppcoreguidelines-pro-type-cstyle-cast,
      cppcoreguidelines-pro-type-reinterpret-cast,
      cppcoreguidelines-pro-type-member-init,
      cppcoreguidelines-pro-type-union-access,
      cppcoreguidelines-prefer-member-initializer,
      cppcoreguidelines-avoid-goto,
      cppcoreguidelines-avoid-non-const-global-variables,
      cppcoreguidelines-init-variables,
      cppcoreguidelines-interfaces-global-init,
      cppcoreguidelines-macro-usage,
      cppcoreguidelines-narrowing-conversions,
      cppcoreguidelines-owning-memory,
      cppcoreguidelines-slicing,
      cppcoreguidelines-special-member-functions,
      hicpp-multiway-paths-covered,
      readability-uppercase-literal-suffix
      ]
    Remove:
      [
        abseil*,
        android*,
        fuchsia*,
        llvmlib*,
        zircon*,
        altera*,
        linuxkernel-*,
        modernize-use-trailing-return-type,
        google-runtime-int,
        cert-err58-cpp,
        hicpp-avoid-c-arrays,
        google-readability-todo,
        modernize-avoid-c-arrays,
        misc-non-private-member-variables-in-classes,
        cppcoreguidelines-pro-type-reinterpret-cast
      ]
    CheckOptions:
        readability-function-size.BranchThreshold: 50,
        readability-function-size.ParameterThreshold: 7,
        readability-function-size.StatementThreshold: 300,
        cppcoreguidelines-pro-type-member-init.UseAssignment: true,
Index:
  Background: Build
CompileFlags:
    Add: [-Wall, -Wextra, -Werror, -fsanitize=undefined, -Wno-format-security, -DNODEBUG, -mavx]
    Compiler: clang++
InlayHints:
    Enabled: No
    ParameterNames: Yes
    DeducedTypes: Yes

