Diagnostics:
  UnusedIncludes: Strict

Index:
  Background: Build
CompileFlags:
    Add: [-Wall, -Wextra, -Werror, -mavx, -std=c++17, -nostdinc++]
    Remove: [-Wduplicated-cond, -Wformat-overflow=2, -Wno-class-memaccess, -fno-lifetime-dse, -fno-lifetime-dse]
    Compiler: clang++
InlayHints:
    Enabled: Yes
    ParameterNames: Yes
    DeducedTypes: Yes
